### ISSUE TITLE
Need import torch first to use it as backend

### ISSUE THREAD

**Issue by royess** [tencent-quantum-lab/tensorcircuit#18]
I found that I need to import torch first to use it as backend. Otherwise there will be an import error.

If I first import torch:
```python
>>> import torch
>>> import tensorcircuit as tc
2022-06-12 18:14:35.855582: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
>>> tc.set_backend("pytorch")
pytorch_backend
```

Otherwise:
```python
>>> import tensorcircuit as tc
2022-06-12 18:11:49.161582: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
>>> tc.set_backend("pytorch")
Traceback (most recent call last):
  File "/home/yuxuan/.julia/conda/3/envs/tc39/lib/python3.9/site-packages/tensornetwork/backends/pytorch/pytorch_backend.py", line 37, in __init__
    import torch
  File "/home/yuxuan/.julia/conda/3/envs/tc39/lib/python3.9/site-packages/torch/__init__.py", line 199, in <module>
    from torch._C import *  # noqa: F403
ImportError: /home/yuxuan/.julia/conda/3/envs/tc39/lib/python3.9/site-packages/torch/lib/libtorch_cuda_cpp.so: undefined symbol: cudaGraphRetainUserObject, version libcudart.so.11.0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yuxuan/.julia/conda/3/envs/tc39/lib/python3.9/site-packages/tensorcircuit/cons.py", line 103, in set_tensornetwork_backend
    backend_obj = get_backend(backend)
  File "/home/yuxuan/.julia/conda/3/envs/tc39/lib/python3.9/site-packages/tensorcircuit/backends/backend_factory.py", line 50, in get_backend
    _INSTANTIATED_BACKENDS[backend] = _BACKENDS[backend]()
  File "/home/yuxuan/.julia/conda/3/envs/tc39/lib/python3.9/site-packages/tensorcircuit/backends/pytorch_backend.py", line 171, in __init__
    super(PyTorchBackend, self).__init__()
  File "/home/yuxuan/.julia/conda/3/envs/tc39/lib/python3.9/site-packages/tensornetwork/backends/pytorch/pytorch_backend.py", line 39, in __init__
    raise ImportError("PyTorch not installed, please switch to a different "
ImportError: PyTorch not installed, please switch to a different backend or install PyTorch.
```

**Comment by refraction-ray** [comment]
I am not sure about you specific torch release. But for me, I have tested pip-installed torch with cuda support and with only cpu, both are ok to ``tc.set_backend("pytorch")`` without firstly ``import torch``

**Comment by refraction-ray** [comment]
And to enjoy fast speed with tensorcircuit, I strongly recommend to use Jax or TensorFlow backend, and you can also enjoy your familiar pytorch pipeline as well, just with a ``tc.interfaces.torch_interface`` wrapper, see an example https://tensorcircuit.readthedocs.io/en/latest/tutorials/torch_qml.html
